merge_cells = false

# unique identifier (for merging)
instance_index = ["ntasks", "alpha", "wmax", "rmax", "seed"]

# columns order for instaces latex table
instance_order = ["W", "nitems", "reff", "lb"]

# columns order for results table
models_order = ["obj", "bound", "runtime"]

# columns order for latex table
algos_order = ["obj", "bound", "runtime"]

# models
models = []

# algorithms
algos = ["bin/heur95", "bin/heur98", "bin/heur100"]

# timelimit
timelimit = 600

# memlimit
memlimit = 16

# threads (0 = all)
threads = 1

# seed
seed = 0
