# unique identifier (for merging)
instance_index = ["ntasks", "alpha", "wmax", "rmax", "seed"]

# columns order for instaces latex table
instance_order = ["W", "nitems", "reff", "lb"]
instance_stats = []

# columns order for results table
models_order = ["obj", "bound", "runtime"]
models_stats = []

# columns order for latex table
algos_order = ["obj", "runtime"]
algos_stats = []

# models
models = ["bin/shelves", "bin/coord", "bin/coord2"]

# algorithms
algos = ["bin/bottom_left"]

# timelimit
timelimit = 3600

# memlimit
memlimit = 16

# threads (0 = all)
threads = 1

# seed
seed = 0